version: '3.2'
services:
    api:
        build: ./api
        depends_on:
            - 'db'
        ports:
            - '8000:8080'
        networks:
            - database
        environment:
            - DB_HOST=db
            - DB_USER=smk
            - DB_PASSWORD=123456
            - DB_NAME=testDb
            - DB_PORT=3306
        container_name: apiApp
    db:
        build: ./db
        container_name: dbApp
        networks:
            - database
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=smk
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=testDb
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        networks:
            - database
        depends_on:
            - 'db'
        ports:
            - '30002:80'
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        volumes:
            - /sessions
        container_name: phpmyadminApp

networks:
    database:
