version: '2'
services:
    api:
        build: ./api
        ports:
            - '6000:8080'
        depends_on:
            - db
        volumes:
            - ./api/volumes/
    # db:
    #     build: ./db
    #     ports:
    #         - '3307:3306'
